repos:
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 22.1.0
      hooks:
          - id: black
            args: [--target-version, 'py310']
            language_version: python3.10
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.0a2
      hooks:
          - id: flake8
    - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
      rev: v1.0.5
      hooks:
          - id: python-bandit-vulnerability-check
            args: [--recursive, server, --recursive, client, --exclude, '**/tests/**.*', --skip, 'B410']
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.910'
      hooks:
          - id: mypy
            additional_dependencies:
                [
                    types-requests==2.25.11,
                ]
